// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nlUFlrQh9tu73BH5UokXCRvgiNfWDtQ',
    appId: '1:55798060141:web:134a30907d1d2ffb1edb64',
    messagingSenderId: '55798060141',
    projectId: 'proyectoprueba-ba0d7',
    authDomain: 'proyectoprueba-ba0d7.firebaseapp.com',
    storageBucket: 'proyectoprueba-ba0d7.appspot.com',
    measurementId: 'G-6HQ0MDH1Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCby-YnKby8TUilePfhdb5sY6LJ9oli98A',
    appId: '1:55798060141:android:43bdf83708b64e401edb64',
    messagingSenderId: '55798060141',
    projectId: 'proyectoprueba-ba0d7',
    storageBucket: 'proyectoprueba-ba0d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCb1mlmwWD3TSRBT7_4nSVj9HeyY4N2HU',
    appId: '1:55798060141:ios:d34446b4faa3cca21edb64',
    messagingSenderId: '55798060141',
    projectId: 'proyectoprueba-ba0d7',
    storageBucket: 'proyectoprueba-ba0d7.appspot.com',
    iosClientId: '55798060141-ahm81gl1l78uqvbvne5v468cv9dubq2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectolineados',
  );
}
